spring:
  application:
    name: rollback-poc
  datasource:
    # docker run --rm --name rollbackdb -e POSTGRES_DB=rollbackdb -e POSTGRES_USER=sa -e POSTGRES_PASSWORD=sa -p 5432:5432 -d postgres
    # PSQL --> docker run -it --rm --link rollbackdb postgres psql -h rollbackdb -U sa -d rollbackdb  --> pass: sa
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:rollbackdb}
    username: ${POSTGRES_USER:sa}
    password: ${POSTGRES_PASS:sa}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:/db/changelog/master.xml
    enabled: ${LIQUIBASE_ENABLED:true}

server:
  port: 8383


